Feature/aos 4102 s3
Skatteetaten/openshift-reference-springboot-server pull request #51
Opened 2020-10-07 08:48 UTC by kris456

2020-10-28 22:07 UTC, bentsolheim requested changes

2020-10-28 22:07 UTC, bentsolheim commented on src/test/groovy/no/skatteetaten/aurora/openshift/reference/springboot/service/S3ServiceTest.groovy
> +@SpringBootTest
Du kan lage en mindre ApplicationContext for denne testen ved å gjøre følgende

```
@RestClientTest
@ContextConfiguration(classes = [ApplicationConfig, S3Service])
```

Da slipper du å fyre opp "hele" contexten + database.

2020-10-28 22:12 UTC, kris456 commented on src/test/groovy/no/skatteetaten/aurora/openshift/reference/springboot/service/S3ServiceTest.groovy
> +@SpringBootTest
Takk, skal teste det. Visste det var en måte:) Prøvd litt forskjellige kombinasjoner, med ikke den der :)

2020-10-28 22:12 UTC, kris456 commented on pom.xml
> +      <version>2.13.1</version>
jepp, good catch

2020-10-31 12:26 UTC, bentsolheim approved these changes

2020-10-31 12:29 UTC, bentsolheim commented on src/test/groovy/no/skatteetaten/aurora/openshift/reference/springboot/service/S3ServiceTest.groovy
> +@ContextConfiguration(classes = [ApplicationConfig, S3Service])
Kunne visst gjøres enda enklere:

```
@RestClientTest([ApplicationConfig, S3Service])
```

2020-11-10 07:41 UTC, bjartek approved these changes

2020-11-17 09:14 UTC, bjartek approved these changes

2020-11-23 13:31 UTC, merged