AOS-5156 Update spring to 2.4.0. Also update dependencies.
Skatteetaten/openshift-reference-springboot-server pull request #53
Opened 2020-12-07 13:18 UTC by nostra

Purpose: General maintenance, and making nexus-iq happy. Needed to add junit-vintage-engine in order to get tests built.

2020-12-09 12:52 UTC, bentsolheim approved these changes

2020-12-09 12:52 UTC, bentsolheim commented on pom.xml
> +      <artifactId>junit-vintage-engine</artifactId>
Er det på grunn av spock man trenger dette? Kanskje vi bør ta en diskusjon på om vi skal gå over til å bruke ren JUnit fremfor spock, slik man gjør i refapp for kotlin?

2020-12-10 09:30 UTC, bjartek approved these changes

2020-12-10 09:31 UTC, bjartek requested changes

2020-12-10 09:31 UTC, bjartek commented on pom.xml
> +    <aurora.starters.version>2.4.0</aurora.starters.version>
Hvilken starter er det vi bruker her? Er det den nye som Jarle og Anders har laget eller den gamle?

2020-12-10 09:33 UTC, nostra commented on pom.xml
> +    <aurora.starters.version>2.4.0</aurora.starters.version>
Jeg var ikke klar over at det eksisterer ulike versjoner av denne avhengigheten. Jeg oppdaterte versjonen fordi oppdatering var tilgjengelig.

2020-12-10 10:21 UTC, nostra commented on pom.xml
> +    <aurora.starters.version>2.4.0</aurora.starters.version>
Det viser seg at 
```
<dependency>
  <groupId>no.skatteetaten.aurora.springboot</groupId>
  <artifactId>aurora-spring-boot-mvc-starter</artifactId>
  <version>${aurora.starters.version}</version>
</dependency>
```
... med versjon v1.0.9 er det riktige. Jeg skal oppdatere PR og reteste.

2020-12-14 11:31 UTC, nostra commented on pom.xml
> +      <artifactId>junit-vintage-engine</artifactId>
Selv om det viste seg at vi må kjøre spring-boot-2.3.7 og ikke 2.4.1 pga sleuth-inkompatibilitet, fjerner jeg ikke den eksplisitte avhengigheten til junit-vintage-engine, siden vi - før eller siden - kommer på spring-boot-2.4

2020-12-14 11:35 UTC, nostra commented on pom.xml
> +    <aurora.starters.version>2.4.0</aurora.starters.version>
Avhengigheten er, etter oppdageringer, 1.0.10. Dette gir springboot-1.3.7.

2020-12-15 07:48 UTC, bjartek approved these changes

2020-12-15 08:04 UTC, merged